const mongoose = require("mongoose");

let cvSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  streetNumber: String,
  postcode: String,
  cityInfo: String,
  countryInfo: String,
  typephone: String,
  phone: String,
  PersonalWebPage: String,
  email: String,
  typeContactMsg: String,
  msgContact: String,
  dayFormBirthday: String,
  monthFormBirthday: String,
  yearFormBirthday: String,
  dateFormatBirthday: String,
  nationality: String,

  application: String,
  applicationDescription: String,

  dateDayExperienceFrom: String,
  dateMonthExperienceFrom: String,
  dateYearExperienceFrom: String,
  dateDayExperienceTo: String,
  dateMonthExperienceTo: String,
  dateYearExperienceTo: String,
  onGoingExperience: Boolean,
  dateFormatExperience: String,
  role: String,
  employer: String,
  cityEmployer: String,
  countryEmployer: String,
  moreDetailExperience: Boolean,
  adressEmployer: String,
  postCodeEmployer: Number,
  websiteEmpployer: String,
  branchActivity: String,
  responsibility: String,

  dateDayEducationFrom: String,
  dateMonthEducationFrom: String,
  dateYearEducationFrom: String,
  dateDayEducationTo: String,
  dateMonthEducationTo: String,
  dateYearEducationTo: String,
  onGoingEducation: Boolean,
  dateFormatEducation: String,
  professionalQualification: String,
  educationalInstitution: String,
  cityEducationalInstitution: String,
  countryEducationalInstituition: String,
  moreDetailEducation: Boolean,
  adressNumberEducationalInstituition: String,
  postCodeEducationalInstituition: Number,
  websiteEducationalInstituition: String,
  nationalClassification: String,
  subjects: String,

  motherLanguage: String,
  comunication: String,
  organization: String,
  workSkills: String,
  foreignLanguage: String,
  oralComprehension: String,
  understandReading: String,
  oralInteraction: String,
  oralProduction: String,
  writing: String,
  diplomaLanguages: String,
  informationProcessing: String,
  informationComunication: String,
  contentCreation: String,
  digitalSecurity: String,
  troubleshooting: String,
  diplomaDigitalSkills: String,
  moreInformaticSkills: String
});

module.exports = mongoose.model("CV", cvSchema);
